name: AaronRobertshaw
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85957
title: Aaron Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131e22'
    - '#455960'
    - '#584125'
    - '#7a642e'
    - '#637e81'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
