name: AaronRobertshaw
favicon: null
layout_spectrum: 0.37117386306636035
typography_spectrum: 0.85957
title: Aaron Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131e22'
    - '#455960'
    - '#584125'
    - '#7a642e'
    - '#637e81'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.44724227068945765
  rhythmicContrast: 0.45145009621046484
purpose: []
